### ISSUE TITLE
RPM for Fedora

### ISSUE THREAD

**Issue by FreedomBen** [mptre/pick#303]
Hello, I've been using pick for years (I remember when it was a brand new project :heart: ) and I've always just built from source since it has never been available in the Fedora repositories and it changes slowly enough that the same install works for years at a time. 

I rebuilt my system for Fedora 32 and realized it is a shame that pick still isn't packaged.  A few questions:

1.  Is anyone working on this already?
2.  Is there any reason why you _don't_ have an RPM currently (besides just nobody to do the work)?
3.  If I built one, would you give it your blessing?
4.  Where is the source for the other packages (like the deb)?

**Comment by mptre** [comment]
> 1.  Is anyone working on this already?

Not that I'm aware of.

> 2.  Is there any reason why you _don't_ have an RPM currently (besides just nobody to do the work)?

No

> 3.  If I built one, would you give it your blessing?

Sure, I use Fedora at $WORK and making pick available as a RPM would be
much appreciated.

> 4.  Where is the source for the other packages (like the deb)?

No idea. Maybe Repology[1] can point you in the right direction.

[1] https://repology.org/project/pick/versions

**Comment by mptre** [comment]
Can this be closed? Feel free to update the readme once the RPM is available.

**Comment by FreedomBen** [comment]
Yes, will do :+1:

**Comment by FreedomBen** [comment]
I'm working on the RPM and the F32 build is failing because of #302 .  Will a new release of pick be cut soon?  For now I'll just build for Fedora 31, so it's not a rush, just hoping to have some idea when to expect the new release.

**Comment by FreedomBen** [comment]
Another thing I've run into:  It doesn't look like the `configure` script is honoring `--prefix` .  Is there a different way to specify the install prefix, or is there a bug in the configure script?

**Comment by mptre** [comment]
> Will a new release of pick be cut soon?

I can release a new version later today.

**Comment by mptre** [comment]
> Another thing I've run into:  It doesn't look like the `configure` script is honoring `--prefix` .  Is there a different way to specify the install prefix, or is there a bug in the configure script?

Try `PREFIX=something ./configure`

**Comment by mptre** [comment]
Version 4.0.0 is now released, including your recent fix. Feel free to
add yourself to the list of package maintainers in order to get notified
on new releases: https://github.com/mptre/pick/blob/master/CONTRIBUTING.md
