### ISSUE TITLE
Reintroduction of the removed version option

### ISSUE THREAD

**Issue by uffejakobsen** [mptre/pick#307]
IMHO removing the version option is a bad thing.

One example I have a script that uses pick as "selector"
It uses (-v) to check that a proper (minimum-)version of pick i found in the path.
The script needs to run on at least 10 different distrubutions
So now this script has to include logic to query10 different package mackage managers - just to query for the version of pick - a check that previously was possible with a simple shell script line is now made difficult and hard to maintain :-(

I would really vote for the reintroduction of the version option to pick

**Comment by mptre** [comment]
Which feature of pick do you need to conditionally check presence of?

**Comment by uffejakobsen** [comment]
> Which feature of pick do you need to conditionally check presence of?

Too many things to everything mention here - just take a look at your release notes history:

v2.0: key CTRL-O introduced
v1.9: ALTERASE (Ctrl-W), option -K introduced
v1.7: keys HOME/END introduced
v1.6: improvements in esc seq matches
v1.4 option -S introduced, key CTRL-D introduced
etc etc etc...

In order to provide a consistent "user interface" we limit the acceptable version of pick to a minimum version

Without knowing the version of pick it is hard to write a consistent and exact user-guide adressing features and/or keys that may not exist.
We would need to say if you are lucky you can find the required sort option on this key - if it doesn't work then your version of pick is probably too old :-S

As a last detail some distributions do not at all have pick in their repo - others have a version that is too old for our minimum limit - so we have to have our own compiled (new) version of pick on some of those systems.
That creates a new variation for us to handle the situation that pick is available via the PATH - but not found in the pkg repo - what version is that I found ?
Another variation: a version of pick is installed - but it is the same pick that I'm "picking" up via the PATH ?

**Comment by mptre** [comment]
Doesn't the following work? `pick -v 2>/dev/null || echo 4.0.0`

It won't cope with any potential future features of course.

**Comment by uffejakobsen** [comment]
> Doesn't the following work? `pick -v 2>/dev/null || echo 4.0.0` 
> It won't cope with any potential future features of course.
No exactly - I won't call it a maintainable solution - it would be nice with some sort of version string
Not that is much work - but will you accept a pull ?

**Comment by mptre** [comment]
> Not that is much work - but will you accept a pull ?

I'm not too eager on reintroducing that option. The proposed work-around
is as stated not future proof but pick is fairly stable in terms of
features at this point.

**Comment by uffejakobsen** [comment]
No, I see - it is also tricky and complex option that would increase the cyclomatic complexity of the project - reaching an almost unmaintainable state and size  :-D

Warning: may contain traces of sarcasm ;-)
